/*----------------------------------------------------------------------*
 * File name	: e2rdrv.h	/ e2rom driver prototype		*
 *----------------------------------------------------------------------*
 *$Header: p:/presto2/shinc/drive/RCS/e2rdrv.h 1.1 1970/01/01 00:00:00 chimura Exp $
 *$Log: e2rdrv.h $
 * リビジョン 1.1  1970/01/01  00:00:00  chimura
 * 初期リビジョン
 * 
 *----------------------------------------------------------------------*/
/*		(c) Copyright 1988, ISHIDA SCALES MFG. CO., LTD.	*/
/*		959-1 SHIMOMAGARI RITTO-CHO KURITA-GUN			*/
/*		SHIGA JAPAN						*/
/*		(0775) 53-4141						*/
/*----------------------------------------------------------------------*/


#if	!defined(E2RDRV_H)
#define	E2RDRV_H

int		e2_sys_init(unsigned short);

#endif	/* E2RDRV_H */

