/*---------------------------------------------------------------------
 * $Header: p:/presto2/shinc/drive/RCS/eth_def.h 1.1 1970/01/01 00:00:00 sakaguti Exp $
 * $Log: eth_def.h $
 * リビジョン 1.1  1970/01/01  00:00:00  sakaguti
 * 新規リビジョン
 * 
*----------------------------------------------------------------------
*		(C) Copyright 2002, ISHIDA CO., LTD.                           
*		959-1 SHIMOMAGARI RITTO-CITY SHIGA JAPAN                       
*		PHONE (077) 553-4141                                           
*----------------------------------------------------------------------*/

#define INADDR_ANY 0
#define NCONNS 14

INTHDR irhan00(void);


