/*---------------------------------------------------------------------
 * $Header: p:/presto2/shinc/drive/RCS/lan_init.h 1.2 1970/01/01 00:00:00 kagatume Exp $
 * $Log: lan_init.h $
 * リビジョン 1.2  1970/01/01  00:00:00  kagatume
 * 2003/11/17 11:15
 * プロトタイプ宣言 int InitLan( void ) の追加
 * 
 * リビジョン 1.1  1970/01/01  00:00:00  sakaguti
 * 新規リビジョン
 * 
*----------------------------------------------------------------------
*		(C) Copyright 2002, ISHIDA CO., LTD.                           
*		959-1 SHIMOMAGARI RITTO-CITY SHIGA JAPAN                       
*		PHONE (077) 553-4141                                           
*----------------------------------------------------------------------*/



int InitLanSystem( void );
int InitLan( void );
