/*----------------------------------------------------------------------*
 * File name	: sramdrv.h	/ sram driver prototype			*
 *----------------------------------------------------------------------*
 *$Header: p:/presto2/shinc/drive/RCS/sramdrv.h 1.1 1970/01/01 00:00:00 chimura Exp $
 *$Log: sramdrv.h $
 * リビジョン 1.1  1970/01/01  00:00:00  chimura
 * 初期リビジョン
 * 
 *----------------------------------------------------------------------*/
/*		(c) Copyright 1988, ISHIDA SCALES MFG. CO., LTD.	*/
/*		959-1 SHIMOMAGARI RITTO-CHO KURITA-GUN			*/
/*		SHIGA JAPAN						*/
/*		(0775) 53-4141						*/
/*----------------------------------------------------------------------*/


#if	!defined(SRAMDRV_H)
#define	SRAMDRV_H

int		sram_sys_init(unsigned short);

#endif	/* SRAMDRV_H */

