/*---------------------------------------------------------------------
* File name	: config.h                                              
*----------------------------------------------------------------------
*$Header: p:/presto/shlib_v7/drive/usnets/usnetsh7/RCS/config.h 1.1 1970/01/01 00:00:00 masahiro Exp $
*$Log: config.h $
 * リビジョン 1.1  1970/01/01  00:00:00  masahiro
 * 初期リビジョン
 * 
*----------------------------------------------------------------------
*		(C) Copyright 2002, ISHIDA CO., LTD.                           
*		959-1 SHIMOMAGARI RITTO-CITY SHIGA JAPAN                       
*		PHONE (077) 553-4141                                           
*----------------------------------------------------------------------*/

#ifndef FAR
/* change to #define FAR far   for DOS compilers */
#define FAR
#endif
