xcopy /k /d /l /r /y p:\e_duc D:\P-Drive\e_duc
xcopy /k /d /l /r /y p:\h8sinc D:\P-Drive\h8sinc
xcopy /k /d /l /r /y p:\h8sinc\bios2357 D:\P-Drive\h8sinc\bios2357
xcopy /k /d /l /r /y p:\h8sinc\custom D:\P-Drive\h8sinc\custom
xcopy /k /d /l /r /y p:\h8sinc\drive D:\P-Drive\h8sinc\drive
xcopy /k /d /l /r /y p:\h8sinc\rom D:\P-Drive\h8sinc\rom
xcopy /k /d /l /r /y p:\h8slib D:\P-Drive\h8slib
xcopy /k /d /l /r /y p:\h8slib\custom D:\P-Drive\h8slib\custom
xcopy /k /d /l /r /y p:\h8slib\custom\src D:\P-Drive\h8slib\custom\src
xcopy /k /d /l /r /y p:\h8slib\custom\src\doc D:\P-Drive\h8slib\custom\src\doc
xcopy /k /d /l /r /y p:\h8slib\drive D:\P-Drive\h8slib\drive
xcopy /k /d /l /r /y p:\h8slib\drive\rsh D:\P-Drive\h8slib\drive\rsh
xcopy /k /d /l /r /y p:\h8slib\drive\sci D:\P-Drive\h8slib\drive\sci
xcopy /k /d /l /r /y p:\h8slib\drive\sci\doc D:\P-Drive\h8slib\drive\sci\doc
xcopy /k /d /l /r /y p:\h8slib\drive\tpu D:\P-Drive\h8slib\drive\tpu
xcopy /k /d /l /r /y p:\h8slib\rom D:\P-Drive\h8slib\rom
xcopy /k /d /l /r /y p:\h8slib\rom\src D:\P-Drive\h8slib\rom\src
xcopy /k /d /l /r /y p:\h8slib\rom\src\doc D:\P-Drive\h8slib\rom\src\doc
xcopy /k /d /l /r /y p:\PRESTO D:\P-Drive\PRESTO
xcopy /k /d /l /r /y p:\PRESTO\mkinf D:\P-Drive\PRESTO\mkinf
xcopy /k /d /l /r /y p:\PRESTO\mkinf\ADDDUMMY D:\P-Drive\PRESTO\mkinf\ADDDUMMY
xcopy /k /d /l /r /y p:\PRESTO\mkinf\ADDDUMMY\new D:\P-Drive\PRESTO\mkinf\ADDDUMMY\new
xcopy /k /d /l /r /y p:\PRESTO\mkinf\ADDDUMMY\org D:\P-Drive\PRESTO\mkinf\ADDDUMMY\org
xcopy /k /d /l /r /y p:\PRESTO\mkinf\cf100 D:\P-Drive\PRESTO\mkinf\cf100
xcopy /k /d /l /r /y p:\PRESTO\mkinf\cf200 D:\P-Drive\PRESTO\mkinf\cf200
xcopy /k /d /l /r /y p:\PRESTO\mkinf\old D:\P-Drive\PRESTO\mkinf\old
xcopy /k /d /l /r /y p:\PRESTO\mkinf\org D:\P-Drive\PRESTO\mkinf\org
xcopy /k /d /l /r /y p:\PRESTO2 D:\P-Drive\PRESTO2
xcopy /k /d /l /r /y p:\PRESTO2\DMU D:\P-Drive\PRESTO2\DMU
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7 D:\P-Drive\PRESTO2\DMU_v7
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\bios D:\P-Drive\PRESTO2\DMU_v7\bios
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\bios\debjtag D:\P-Drive\PRESTO2\DMU_v7\bios\debjtag
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\bios\src D:\P-Drive\PRESTO2\DMU_v7\bios\src
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\bios\t0017 D:\P-Drive\PRESTO2\DMU_v7\bios\t0017
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\bios\t0018 D:\P-Drive\PRESTO2\DMU_v7\bios\t0018
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\bios\t0018\ORG D:\P-Drive\PRESTO2\DMU_v7\bios\t0018\ORG
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\bios\t0018\ORG\bk0 D:\P-Drive\PRESTO2\DMU_v7\bios\t0018\ORG\bk0
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\bootload D:\P-Drive\PRESTO2\DMU_v7\bootload
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\bootload\t0026 D:\P-Drive\PRESTO2\DMU_v7\bootload\t0026
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\T0051 D:\P-Drive\PRESTO2\DMU_v7\T0051
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\T0051\dwfinf D:\P-Drive\PRESTO2\DMU_v7\T0051\dwfinf
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\T0051\org D:\P-Drive\PRESTO2\DMU_v7\T0051\org
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\T0051\org\bk0 D:\P-Drive\PRESTO2\DMU_v7\T0051\org\bk0
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\T0051\org\bk1 D:\P-Drive\PRESTO2\DMU_v7\T0051\org\bk1
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\T0051\org\bk2 D:\P-Drive\PRESTO2\DMU_v7\T0051\org\bk2
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\T0051\org\bk3 D:\P-Drive\PRESTO2\DMU_v7\T0051\org\bk3
xcopy /k /d /l /r /y p:\PRESTO2\DMU_v7\T0051\org\bk4 D:\P-Drive\PRESTO2\DMU_v7\T0051\org\bk4
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE D:\P-Drive\PRESTO2\DMU\INCLUDE
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE\BANK D:\P-Drive\PRESTO2\DMU\INCLUDE\BANK
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE\BANK\RCULIB D:\P-Drive\PRESTO2\DMU\INCLUDE\BANK\RCULIB
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE\GLIB D:\P-Drive\PRESTO2\DMU\INCLUDE\GLIB
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE\LINE D:\P-Drive\PRESTO2\DMU\INCLUDE\LINE
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE\LROM D:\P-Drive\PRESTO2\DMU\INCLUDE\LROM
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE\RCULIB D:\P-Drive\PRESTO2\DMU\INCLUDE\RCULIB
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE\SYSdummy D:\P-Drive\PRESTO2\DMU\INCLUDE\SYSdummy
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE\SYSdummy\target D:\P-Drive\PRESTO2\DMU\INCLUDE\SYSdummy\target
xcopy /k /d /l /r /y p:\PRESTO2\DMU\INCLUDE\SYSdummy\target\h D:\P-Drive\PRESTO2\DMU\INCLUDE\SYSdummy\target\h
xcopy /k /d /l /r /y p:\PRESTO2\DMU\main D:\P-Drive\PRESTO2\DMU\main
xcopy /k /d /l /r /y p:\PRESTO2\DMU\main\comm100 D:\P-Drive\PRESTO2\DMU\main\comm100
xcopy /k /d /l /r /y p:\PRESTO2\DMU\r4308 D:\P-Drive\PRESTO2\DMU\r4308
xcopy /k /d /l /r /y p:\PRESTO2\HEW D:\P-Drive\PRESTO2\HEW
xcopy /k /d /l /r /y p:\PRESTO2\HEW\TOOLS D:\P-Drive\PRESTO2\HEW\TOOLS
xcopy /k /d /l /r /y p:\PRESTO2\HEW\TOOLS\HITACHI D:\P-Drive\PRESTO2\HEW\TOOLS\HITACHI
xcopy /k /d /l /r /y p:\PRESTO2\HEW\TOOLS\HITACHI\SH D:\P-Drive\PRESTO2\HEW\TOOLS\HITACHI\SH
xcopy /k /d /l /r /y p:\PRESTO2\HEW\TOOLS\HITACHI\SH\7_1_1 D:\P-Drive\PRESTO2\HEW\TOOLS\HITACHI\SH\7_1_1
xcopy /k /d /l /r /y p:\PRESTO2\HEW\TOOLS\HITACHI\SH\7_1_1\lib D:\P-Drive\PRESTO2\HEW\TOOLS\HITACHI\SH\7_1_1\lib
xcopy /k /d /l /r /y p:\PRESTO2\mkinf D:\P-Drive\PRESTO2\mkinf
xcopy /k /d /l /r /y p:\PRESTO2\mkinf\cf100 D:\P-Drive\PRESTO2\mkinf\cf100
xcopy /k /d /l /r /y p:\PRESTO2\mkinf\cf200 D:\P-Drive\PRESTO2\mkinf\cf200
xcopy /k /d /l /r /y p:\PRESTO2\mkinf\old D:\P-Drive\PRESTO2\mkinf\old
xcopy /k /d /l /r /y p:\PRESTO2\mkinf\org D:\P-Drive\PRESTO2\mkinf\org
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12 D:\P-Drive\PRESTO2\NORTI_12
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\CTX D:\P-Drive\PRESTO2\NORTI_12\CTX
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\CTX\SH D:\P-Drive\PRESTO2\NORTI_12\CTX\SH
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\CTX\SH\SHC5 D:\P-Drive\PRESTO2\NORTI_12\CTX\SH\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\CTX\SH\SHC7 D:\P-Drive\PRESTO2\NORTI_12\CTX\SH\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\DOC D:\P-Drive\PRESTO2\NORTI_12\DOC
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\INC D:\P-Drive\PRESTO2\NORTI_12\INC
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\INC\Dummy D:\P-Drive\PRESTO2\NORTI_12\INC\Dummy
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\LIB D:\P-Drive\PRESTO2\NORTI_12\LIB
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\LIB\SH D:\P-Drive\PRESTO2\NORTI_12\LIB\SH
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\LIB\SH\DMUDEB D:\P-Drive\PRESTO2\NORTI_12\LIB\SH\DMUDEB
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\LIB\SH\SHC5 D:\P-Drive\PRESTO2\NORTI_12\LIB\SH\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\LIB\SH\SHC7 D:\P-Drive\PRESTO2\NORTI_12\LIB\SH\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\NETSMP D:\P-Drive\PRESTO2\NORTI_12\NETSMP
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\NETSMP\INC D:\P-Drive\PRESTO2\NORTI_12\NETSMP\INC
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\NETSMP\SRC D:\P-Drive\PRESTO2\NORTI_12\NETSMP\SRC
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP D:\P-Drive\PRESTO2\NORTI_12\SMP
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH D:\P-Drive\PRESTO2\NORTI_12\SMP\SH
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MiNET_7042 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MiNET_7042
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\ROMICE64 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\ROMICE64
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC5\net7042_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC5\net7042_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC5\smp7042_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC5\smp7042_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC7\net7042_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC7\net7042_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC7\smp7042_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MiNET_7042\SHC7\smp7042_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7615 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7615
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7615\HUDI D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7615\HUDI
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC5\net7615_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC5\net7615_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC5\smp7615_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC5\smp7615_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC7\net7615_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC7\net7615_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC7\smp7615_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7615\SHC7\smp7615_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709\ROMICE64 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709\ROMICE64
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709\SHC7\net7709_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709\SHC7\net7709_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709\SHC7\smp7709_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709\SHC7\smp7709_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709A D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709A
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709A\HUDI D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709A\HUDI
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709A\ROMICE64 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709A\ROMICE64
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC5\net7709a_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC5\net7709a_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC5\smp7709a_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC5\smp7709a_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC7\net7709a_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC7\net7709a_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC7\smp7709a_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7709A\SHC7\smp7709a_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7727 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7727
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7727\HUDI D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7727\HUDI
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7727\ROMICE64 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7727\ROMICE64
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC5\net7727_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC5\net7727_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC5\smp7727_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC5\smp7727_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC7\net7727_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC7\net7727_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC7\smp7727_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7727\SHC7\smp7727_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7729R D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7729R
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7729R\HUDI D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7729R\HUDI
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7729R\ROMICE64 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7729R\ROMICE64
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC5\net7729R D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC5\net7729R
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC5\smp7729R D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC5\smp7729R
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC7\net7729R D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC7\net7729R
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC7\smp7729R D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7729R\SHC7\smp7729R
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7750 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7750
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7750\HUDI D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7750\HUDI
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC5\net7750_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC5\net7750_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC5\smp7750_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC5\smp7750_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC7\net7750_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC7\net7750_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC7\smp7750_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7750\SHC7\smp7750_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7751 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7751
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7751\HUDI D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7751\HUDI
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC5\NET7751_HEW D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC5\NET7751_HEW
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC5\SMP7751_HEW D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC5\SMP7751_HEW
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC7\NET7751_HEW D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC7\NET7751_HEW
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC7\SMP7751_HEW D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\MS7751\SHC7\SMP7751_HEW
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\ROMICE64 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\ROMICE64
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\SHC5\smp7055_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\SHC5\smp7055_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\SHC7\smp7055_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7055_EVA_BOD\SHC7\smp7055_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\HUDI D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\HUDI
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC5\net7615_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC5\net7615_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC5\smp7615_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC5\smp7615_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC7\net7615_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC7\net7615_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC7\smp7615_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7615_EVA_BOD\SHC7\smp7615_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\HUDI D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\HUDI
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\SHC5\smp7729_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\SHC5\smp7729_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\SHC7\smp7729_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7729_EVA_BOD\SHC7\smp7729_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\HUDI D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\HUDI
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\ROMICE64 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\ROMICE64
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\SHC5 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\SHC5\Smp7750_Hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\SHC5\Smp7750_Hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\SHC7 D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\SHC7\Smp7750_hew D:\P-Drive\PRESTO2\NORTI_12\SMP\SH\SH7750_EVA_BOD\SHC7\Smp7750_hew
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\SRC D:\P-Drive\PRESTO2\NORTI_12\SRC
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\YDC D:\P-Drive\PRESTO2\NORTI_12\YDC
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\YDC\SH D:\P-Drive\PRESTO2\NORTI_12\YDC\SH
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\YDC\SH\SHC5 D:\P-Drive\PRESTO2\NORTI_12\YDC\SH\SHC5
xcopy /k /d /l /r /y p:\PRESTO2\NORTI_12\YDC\SH\SHC7 D:\P-Drive\PRESTO2\NORTI_12\YDC\SH\SHC7
xcopy /k /d /l /r /y p:\PRESTO2\SHINC D:\P-Drive\PRESTO2\SHINC
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\BIOSIF D:\P-Drive\PRESTO2\SHINC\BIOSIF
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\CUSTOM D:\P-Drive\PRESTO2\SHINC\CUSTOM
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\DRIVE D:\P-Drive\PRESTO2\SHINC\DRIVE
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\DRIVE\FSSVR60 D:\P-Drive\PRESTO2\SHINC\DRIVE\FSSVR60
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\DRIVE\FSSVR60_1_9 D:\P-Drive\PRESTO2\SHINC\DRIVE\FSSVR60_1_9
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\DRIVE\FSSVR60_1_9_OLD D:\P-Drive\PRESTO2\SHINC\DRIVE\FSSVR60_1_9_OLD
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\DRIVE\FSSVR60_OLD D:\P-Drive\PRESTO2\SHINC\DRIVE\FSSVR60_OLD
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\DRIVE\SH7615 D:\P-Drive\PRESTO2\SHINC\DRIVE\SH7615
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\DZCMD D:\P-Drive\PRESTO2\SHINC\DZCMD
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\NZCMD D:\P-Drive\PRESTO2\SHINC\NZCMD
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\PRCMD D:\P-Drive\PRESTO2\SHINC\PRCMD
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\ROM D:\P-Drive\PRESTO2\SHINC\ROM
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\RXIF D:\P-Drive\PRESTO2\SHINC\RXIF
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\RZCMD D:\P-Drive\PRESTO2\SHINC\RZCMD
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\RZCMD\doc D:\P-Drive\PRESTO2\SHINC\RZCMD\doc
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\SH7615 D:\P-Drive\PRESTO2\SHINC\SH7615
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\SH7706 D:\P-Drive\PRESTO2\SHINC\SH7706
xcopy /k /d /l /r /y p:\PRESTO2\SHINC\USNETS D:\P-Drive\PRESTO2\SHINC\USNETS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7 D:\P-Drive\PRESTO2\shlib_v7
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF D:\P-Drive\PRESTO2\shlib_v7\BIOSIF
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\ARCNET D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\ARCNET
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\CF D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\CF
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\DADC D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\DADC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\DPMEM D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\DPMEM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\E2ROM D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\E2ROM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\E2SROM D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\E2SROM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\FIFO D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\FIFO
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\FLASH D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\FLASH
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\ICU D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\ICU
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\INIT D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\INIT
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\M66230 D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\M66230
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\PPI D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\PPI
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\RTC D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\RTC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\SCU D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\SCU
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\SRAM D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\SRAM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\TCU D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\TCU
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\BIOSIF\XAM D:\P-Drive\PRESTO2\shlib_v7\BIOSIF\XAM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\CNV D:\P-Drive\PRESTO2\shlib_v7\CNV
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\CNV\OLD D:\P-Drive\PRESTO2\shlib_v7\CNV\OLD
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\CNV\OLD\050930 D:\P-Drive\PRESTO2\shlib_v7\CNV\OLD\050930
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\CNV\SRC D:\P-Drive\PRESTO2\shlib_v7\CNV\SRC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\CNV\test D:\P-Drive\PRESTO2\shlib_v7\CNV\test
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\CUSTOM D:\P-Drive\PRESTO2\shlib_v7\CUSTOM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\CUSTOM\SRC D:\P-Drive\PRESTO2\shlib_v7\CUSTOM\SRC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE D:\P-Drive\PRESTO2\shlib_v7\DRIVE
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\ARCNET D:\P-Drive\PRESTO2\shlib_v7\DRIVE\ARCNET
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\ARCNETA D:\P-Drive\PRESTO2\shlib_v7\DRIVE\ARCNETA
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\CF D:\P-Drive\PRESTO2\shlib_v7\DRIVE\CF
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\DPMEM D:\P-Drive\PRESTO2\shlib_v7\DRIVE\DPMEM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\E2ROM D:\P-Drive\PRESTO2\shlib_v7\DRIVE\E2ROM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\E2SROM D:\P-Drive\PRESTO2\shlib_v7\DRIVE\E2SROM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FIFO D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FIFO
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FIFO\FIFOARC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FIFO\FIFOARC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FIFO\FIFOSCUC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FIFO\FIFOSCUC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FLASH D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FLASH
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FS D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\DOC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\DOC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\DOC\tool D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\DOC\tool
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT\API D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT\API
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT\COMMON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT\COMMON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT\OS D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT\OS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT\OS\ITRON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\FAT\OS\ITRON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\LIB D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\LIB
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\PCATA D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\PCATA
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\RAMDISK D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\RAMDISK
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY\API D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY\API
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY\COMMON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY\COMMON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY\OS D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY\OS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY\OS\ITRON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY\OS\ITRON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY2 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY2
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY2\060322 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_1_9\UTILITY2\060322
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\DOC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\DOC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT\API D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT\API
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT\COMMON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT\COMMON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT\OS D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT\OS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT\OS\ITRON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\FAT\OS\ITRON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\LIB D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\LIB
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\PCATA D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\PCATA
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\RAMDISK D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\RAMDISK
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\test D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\test
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY\API D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY\API
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY\COMMON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY\COMMON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY\OS D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY\OS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY\OS\ITRON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY\OS\ITRON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY2 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60_OLD\UTILITY2
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\DOC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\DOC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\DOC\tool D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\DOC\tool
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT\API D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT\API
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT\COMMON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT\COMMON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT\OS D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT\OS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT\OS\ITRON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\FAT\OS\ITRON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\LIB D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\LIB
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\PCATA D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\PCATA
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\RAMDISK D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\RAMDISK
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY\API D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY\API
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY\COMMON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY\COMMON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY\OS D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY\OS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY\OS\ITRON D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY\OS\ITRON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY2 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY2
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY2\060322 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\FSSVR60\UTILITY2\060322
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\MPSC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\MPSC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\NDADC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\NDADC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\PDADC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\PDADC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\PDADC\old D:\P-Drive\PRESTO2\shlib_v7\DRIVE\PDADC\old
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\PDADC\old\031006 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\PDADC\old\031006
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\PDADC\old\040705 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\PDADC\old\040705
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\PDADC\old\060417 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\PDADC\old\060417
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\PPI D:\P-Drive\PRESTO2\shlib_v7\DRIVE\PPI
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\RTC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\RTC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU\m66230 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU\m66230
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU\sh7615 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU\sh7615
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU\sh7615\sci D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU\sh7615\sci
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU\sh7615\scic D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU\sh7615\scic
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU\sh7615\scic2 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU\sh7615\scic2
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU\sh7706 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU\sh7706
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU\sh7706\scu D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU\sh7706\scu
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU\sh7706\scuc D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU\sh7706\scuc
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SCU\sh7706\scum D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SCU\sh7706\scum
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SH7615 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SH7615
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SH7615\ether D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SH7615\ether
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\SRAM D:\P-Drive\PRESTO2\shlib_v7\DRIVE\SRAM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\TIMER D:\P-Drive\PRESTO2\shlib_v7\DRIVE\TIMER
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\CONFIG D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\CONFIG
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\CONFIG\SH7615 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\CONFIG\SH7615
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\CONFIG\SH7615\HITACHI D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\CONFIG\SH7615\HITACHI
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\DOC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\DOC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\DRVSRC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\DRVSRC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\DRVSRC\SH7615 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\DRVSRC\SH7615
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\DRVSRC\SH7615\HITACHI D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\DRVSRC\SH7615\HITACHI
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\INCLUDE D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\INCLUDE
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\INCLUDE\RTOS D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\INCLUDE\RTOS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\INCLUDE\RTOS\NORTI4 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\INCLUDE\RTOS\NORTI4
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\NETSRC D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\NETSRC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\NETSVR60 D:\P-Drive\PRESTO2\shlib_v7\DRIVE\USNETS\USNETSH7\NETSVR60
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DRIVE\VDPM D:\P-Drive\PRESTO2\shlib_v7\DRIVE\VDPM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DZCMD D:\P-Drive\PRESTO2\shlib_v7\DZCMD
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DZCMD\old D:\P-Drive\PRESTO2\shlib_v7\DZCMD\old
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DZCMD\old\030925 D:\P-Drive\PRESTO2\shlib_v7\DZCMD\old\030925
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DZCMD\old\041028 D:\P-Drive\PRESTO2\shlib_v7\DZCMD\old\041028
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\DZCMD\src D:\P-Drive\PRESTO2\shlib_v7\DZCMD\src
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MISC D:\P-Drive\PRESTO2\shlib_v7\MISC
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MISC\ARCNET D:\P-Drive\PRESTO2\shlib_v7\MISC\ARCNET
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MISC\dmu5562 D:\P-Drive\PRESTO2\shlib_v7\MISC\dmu5562
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MISC\dmu5562\bak D:\P-Drive\PRESTO2\shlib_v7\MISC\dmu5562\bak
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MISC\FS D:\P-Drive\PRESTO2\shlib_v7\MISC\FS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MISC\FS\bak D:\P-Drive\PRESTO2\shlib_v7\MISC\FS\bak
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MISC\NET D:\P-Drive\PRESTO2\shlib_v7\MISC\NET
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MISC\WCU5561 D:\P-Drive\PRESTO2\shlib_v7\MISC\WCU5561
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MON D:\P-Drive\PRESTO2\shlib_v7\MON
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MON\NZ D:\P-Drive\PRESTO2\shlib_v7\MON\NZ
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\MON\PRESTO D:\P-Drive\PRESTO2\shlib_v7\MON\PRESTO
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\NORTI D:\P-Drive\PRESTO2\shlib_v7\NORTI
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\NORTI\USERLIB D:\P-Drive\PRESTO2\shlib_v7\NORTI\USERLIB
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\NORTI\USERLIB\DMU D:\P-Drive\PRESTO2\shlib_v7\NORTI\USERLIB\DMU
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\NORTI\USERLIB\WCU D:\P-Drive\PRESTO2\shlib_v7\NORTI\USERLIB\WCU
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\NZCMD D:\P-Drive\PRESTO2\shlib_v7\NZCMD
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\NZCMD\src D:\P-Drive\PRESTO2\shlib_v7\NZCMD\src
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\NZCMDX D:\P-Drive\PRESTO2\shlib_v7\NZCMDX
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\NZCMDX\src D:\P-Drive\PRESTO2\shlib_v7\NZCMDX\src
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMD D:\P-Drive\PRESTO2\shlib_v7\PRCMD
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMD\bakup D:\P-Drive\PRESTO2\shlib_v7\PRCMD\bakup
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMD\old D:\P-Drive\PRESTO2\shlib_v7\PRCMD\old
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMD\old\040206 D:\P-Drive\PRESTO2\shlib_v7\PRCMD\old\040206
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMD\old\040518 D:\P-Drive\PRESTO2\shlib_v7\PRCMD\old\040518
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMD\old\040528 D:\P-Drive\PRESTO2\shlib_v7\PRCMD\old\040528
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMD\old\040929 D:\P-Drive\PRESTO2\shlib_v7\PRCMD\old\040929
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMD\src D:\P-Drive\PRESTO2\shlib_v7\PRCMD\src
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX D:\P-Drive\PRESTO2\shlib_v7\PRCMDX
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\031211 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\031211
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\040503 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\040503
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\040810 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\040810
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\041206 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\041206
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\050216 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\050216
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\050301 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\050301
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\050322 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\050322
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\050629 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\050629
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\050709 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\050709
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\050721 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\050721
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\051004 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\051004
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\060614 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\060614
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\061026 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\061026
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\061109 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\061109
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\070111 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\070111
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\070221 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\070221
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\070315 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\070315
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\070320 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\070320
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\071012 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\071012
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\old\120215 D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\old\120215
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\PRCMDX\src D:\P-Drive\PRESTO2\shlib_v7\PRCMDX\src
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\ROM D:\P-Drive\PRESTO2\shlib_v7\ROM
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\ROM\old D:\P-Drive\PRESTO2\shlib_v7\ROM\old
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\ROM\src D:\P-Drive\PRESTO2\shlib_v7\ROM\src
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\ROM\src\test D:\P-Drive\PRESTO2\shlib_v7\ROM\src\test
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\RZCMD D:\P-Drive\PRESTO2\shlib_v7\RZCMD
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\RZCMD\src D:\P-Drive\PRESTO2\shlib_v7\RZCMD\src
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\RZCMDX D:\P-Drive\PRESTO2\shlib_v7\RZCMDX
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\RZCMDX\src D:\P-Drive\PRESTO2\shlib_v7\RZCMDX\src
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\WCU D:\P-Drive\PRESTO2\shlib_v7\WCU
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\WCU\BIOS D:\P-Drive\PRESTO2\shlib_v7\WCU\BIOS
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\WCU\BIOS\src D:\P-Drive\PRESTO2\shlib_v7\WCU\BIOS\src
xcopy /k /d /l /r /y p:\PRESTO2\shlib_v7\WCU\BIOS\t0029 D:\P-Drive\PRESTO2\shlib_v7\WCU\BIOS\t0029
xcopy /k /d /l /r /y p:\PRESTO2\WCU_V7 D:\P-Drive\PRESTO2\WCU_V7
xcopy /k /d /l /r /y p:\PRESTO2\WCU_V7\BIOS D:\P-Drive\PRESTO2\WCU_V7\BIOS
xcopy /k /d /l /r /y p:\presto4 D:\P-Drive\presto4
xcopy /k /d /l /r /y p:\presto4\shlib_v7 D:\P-Drive\presto4\shlib_v7
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive D:\P-Drive\presto4\shlib_v7\drive
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\SH7615 D:\P-Drive\presto4\shlib_v7\drive\SH7615
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\SH7615\ether D:\P-Drive\presto4\shlib_v7\drive\SH7615\ether
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets D:\P-Drive\presto4\shlib_v7\drive\usnets
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7 D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\CONFIG D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\CONFIG
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\CONFIG\SH7615 D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\CONFIG\SH7615
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\CONFIG\SH7615\HITACHI D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\CONFIG\SH7615\HITACHI
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\DOC D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\DOC
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\DRVSRC D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\DRVSRC
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\DRVSRC\SH7615 D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\DRVSRC\SH7615
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\DRVSRC\SH7615\HITACHI D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\DRVSRC\SH7615\HITACHI
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\INCLUDE D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\INCLUDE
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\INCLUDE\RTOS D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\INCLUDE\RTOS
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\INCLUDE\RTOS\NORTI4 D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\INCLUDE\RTOS\NORTI4
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\NETSRC D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\NETSRC
xcopy /k /d /l /r /y p:\presto4\shlib_v7\drive\usnets\USNETSH7\NETSVR60 D:\P-Drive\presto4\shlib_v7\drive\usnets\USNETSH7\NETSVR60
xcopy /k /d /l /r /y p:\tool D:\P-Drive\tool
xcopy /k /d /l /r /y p:\tool\perl D:\P-Drive\tool\perl
xcopy /k /d /l /r /y p:\tool\perl\ver5win3 D:\P-Drive\tool\perl\ver5win3
