;for ROMICE64
INPUT vec7709ah net7709 initsh n4i7709a nosio
INPUT nos7709a nonethw dp8390 nontftp nonecho
INPUT nonechc nonteld nonshel nonftpd nonfile
INPUT noncons nonramd nonping nondump nontelc
INPUT nonftpc nonelan nondhcp nonedns nos16550
INPUT nonecfg
OUTPUT net7709alh
LIBRARY ..\..\..\..\LIB\SH\SHC7\n4dsh3l
LIBRARY ..\..\..\..\LIB\SH\SHC7\n4esh3l
LIBRARY C:\Hew2\Tools\Hitachi\Sh\7_1_1\lib\shc3npl
ROM D=R
START VECT/080000000,P,C,D/080001000,R,B,STACK/08C000000
