INPUT vec7727h net7727 initsh n4i7727 nosio
INPUT nos7727 nonethw dp8390 nontftp nonecho
INPUT nonechc nonteld nonshel nonftpd nonfile
INPUT noncons nonramd nonping nondump nontelc
INPUT nonftpc nonelan nondhcp nonedns nos16550
INPUT nonecfg
OUTPUT net7727bh
LIBRARY ..\..\..\..\LIB\SH\SHC7\n4dsh3b
LIBRARY ..\..\..\..\LIB\SH\SHC7\n4esh3b
LIBRARY C:\Hew2\Tools\Hitachi\Sh\7_1_1\lib\shc3npb
ROM D=R
START VECT/080000000,P,C,D/080001000,R,B,STACK/08C000000
