PRINT net7727lhr
INPUT vec7727h net7727 initsh n4i7727 nosio
INPUT nos7727 nonethw dp8390 nontftp nonecho
INPUT nonechc nonteld nonshel nonftpd nonfile
INPUT noncons nonramd nonping nondump nontelc
INPUT nonftpc nonelan nondhcp nonedns nos16550
INPUT nonecfg
OUTPUT net7727lhr
LIBRARY ..\..\..\..\LIB\SH\SHC5\n4dsh3l
LIBRARY ..\..\..\..\LIB\SH\SHC5\n4esh3l
LIBRARY C:\Hew\Tools\Hitachi\Sh\5_1_0\lib\shc3npl
DEBUG
START VECT(08C000000),P,C,D,R,B,STACK(08C001000)
FORM A
EXIT
