MY_WORK_BASE=p:\presto2
MY_WORK_BASE2=p:\presto2
INC_BASE=p:\presto2\shinc
SHC_INC=p:\PRESTO2\hew\tools\hitachi\sh\7_1_1\include
NORTI_BASE=p:\presto2\norti_12
USNET_BASE=p:\presto2\shlib_v7\drive\usnets\usnetsh7
DEBUGMODE=0
include T0051.MK
