/*======================================================================
 * File name    : rzprm.h
 * Original	: 
 *----------------------------------------------------------------------
 * Function	:
 *	ƒpƒ‰ƒ[ƒ^‹y‚Ñ’è”“™
 *----------------------------------------------------------------------
 *$Header: p:/presto2/shinc/rzcmd/RCS/rzprm.h 1.1 1970/01/01 00:00:00 chimura Exp $
 *$Log: rzprm.h $
 * ƒŠƒrƒWƒ‡ƒ“ 1.1  1970/01/01  00:00:00  chimura
 * ‰ŠúƒŠƒrƒWƒ‡ƒ“
 * 
 *----------------------------------------------------------------------
 *Header: p:/include/rzcmd/rcs/rzprm.h 1.2 1997/12/04 14:27:27 itami
 *Log: rzprm.h
 * ƒŠƒrƒWƒ‡ƒ“ 1.2  1997/12/04  14:27:27  itami
 * NHIC’Ç‰Á
 *----------------------------------------------------------------------
 *		(c) Copyright 1994, ISHIDA CO., LTD.
 *		959-1 SHIMOMAGARI RITTO-CHO KURITA-GUN SHIGA JAPAN
 *		(0775) 53-4141
 *======================================================================
 */

#if	!defined(RZPRM_H)
#define	RZPRM_H

enum rzprm001e {			/* ƒ{[ƒh”Ô†			*/
	BORD_RCU,			/* ‚q‚b‚t			*/
	BORD_ICU,			/* ‚h‚b‚t			*/
	BORD_WCU,			/* ‚v‚b‚t			*/
	BORD_DUC,			/* ‚c‚t‚b			*/
	BORD_EXC,			/* ‚d‚w‚b			*/
	BORD_ADC,			/* ‚`‚c‚b 			*/
	BORD_NHIC,			/* ‚m‚g‚h‚b			*/
};

#endif
