set SH_COMPILER_BASE=C:\usr\local\SH2\HEW\TOOLS\HITACHI\SH\7_1_1
SET NORTI_BASE=D:\HOME\PDRV\PRESTO4\NORTI_12
SET SHC_ROOT=%SH_COMPILER_BASE%
SET SHC_LIB=%SH_COMPILER_BASE%\bin
SET SHC_INC=%SH_COMPILER_BASE%\include
SET SHC_TMP=C:\TEMP
SET DOS16M= @1M-15M
SET HOME=d:

PATH=D:\HOME\PDRV\PRESTO\OPUS\W95;%SH_COMPILER_BASE%\BIN;%SH_COMPILER_BASE%\include;%NORTI_BASE%\inc;%PATH%

mode con rate=32 delay=1
