set SH_COMPILER_BASE=D:\PRESTO\hew\tools\hitachi\sh\7_1_1
SET NORTI_BASE=c:\norti_12
set MY_WORK_BASE=d:\presto

cd %MY_WORK_BASE%
SET SHC_ROOT=%SH_COMPILER_BASE%
SET SHC_LIB=%SH_COMPILER_BASE%\bin
SET SHC_INC=%SH_COMPILER_BASE%\include
SET SHC_TMP=C:\TEMP
SET DOS16M= @1M-15M
SET HOME=c:

PATH=d:\opus\w95;%SH_COMPILER_BASE%\BIN;%SH_COMPILER_BASE%\include;%NORTI_BASE%\inc;C:\WINDOWS;C:\WINDOWS\COMMAND;C:\HOME\BAT;C:\DOS\UTIL;C:\DOS\MIFES;C:\USR\BIN;

mode con rate=32 delay=1
