MY_WORK_BASE=p:\presto
INC_BASE=p:\presto\shinc
SHC_INC=p:\PRESTO\hew\tools\hitachi\sh\7_1_3\include
NORTI_BASE=p:\presto\norti_12
USNET_BASE=p:\presto\shlib_v7\drive\usnets\usnetsh7
DEBUGMODE=0
include T0017.MK
