/*----------------------------------------------------------------------*
 * File name	: xmath.h	/ mathematics function			*
 *----------------------------------------------------------------------*
 *$Header: p:/presto2/shinc/custom/RCS/xmath.h 1.1 1970/01/01 00:00:00 chimura Exp $
 *$Log: xmath.h $
 * リビジョン 1.1  1970/01/01  00:00:00  chimura
 * 初期リビジョン
 * 
 *----------------------------------------------------------------------*/
/*		(c) Copyright 1988, ISHIDA SCALES MFG. CO., LTD.	*/
/*		959-1 SHIMOMAGARI RITTO-CHO KURITA-GUN			*/
/*		SHIGA JAPAN						*/
/*		(0775) 53-4141						*/
/*----------------------------------------------------------------------*/

#if	!defined(XMATH_H)
#define	XMATH_H

/* function prototypes */

long	h_idiv(long, short);
long	h_imul(short, short);

#endif	/* XMATH_H */

